# Структуровані масиви даних

In [1]:
def homework(message):
    print("\n>>>>>", message, "\n")
import numpy as np


# Визначення однорідного масиву

In [3]:
lst = [ [3.4, 8.7, 9.9], 
        [1.1, -7.8, -0.7],
        [4.1, 12.3, 4.8] ]

# Масив із цілими числами (int8)
A = np.array(lst, dtype=np.int8)
print(f"Отриманий масив має вигляд:\n{repr(A)}")

# Масив із числами у форматі float16
B = np.array(lst, dtype=np.float16)
print(f"Отриманий масив має вигляд:\n{repr(B)}")


Отриманий масив має вигляд:
array([[ 3,  8,  9],
       [ 1, -7,  0],
       [ 4, 12,  4]], dtype=int8)
Отриманий масив має вигляд:
array([[ 3.4,  8.7,  9.9],
       [ 1.1, -7.8, -0.7],
       [ 4.1, 12.3,  4.8]], dtype=float16)


# Задаємо свій тип даних

In [6]:
import numpy as np

# Описуємо спеціальний тип даних із полями:
# 'name' — рядок довжиною до 20 символів, 
# 'mark' — цілі числа (int8).
dt = np.dtype([('name', 'U20'), ('mark', np.int8)])  # 'U20' — рядок довжиною до 20 символів.

# Створюємо список даних у форматі кортежів
arr = [
    ("Bohdan", 4),  # Перший студент із оцінкою 4
    ("Marta", 5),   # Другий студент із оцінкою 5
    ("Noname", 0)   # Третій студент із оцінкою 0
]

# Перетворення списку на структурований масив
C = np.array(arr, dtype=dt)

# Вивід масиву
print(f"Отриманий масив має вигляд:\n{C}")

# Доступ до окремої колонки 'mark'
print(f"Доступитись до певної колонки тепер можна за її іменем: {C['mark']}")

# Вивід усіх імен
print(f"Імена всіх студентів у масиві: {C['name']}")


Отриманий масив має вигляд:
[('Bohdan', 4) ('Marta', 5) ('Noname', 0)]
Доступитись до певної колонки тепер можна за її іменем: [4 5 0]
Імена всіх студентів у масиві: ['Bohdan' 'Marta' 'Noname']


# Запис та зчитування з файлу, формат CSV

In [11]:
import numpy as np
import os

# Створюємо структуру масиву з додатковим полем 'group'
dt = np.dtype([('name', 'U20'), ('mark', np.int8), ('group', 'U10')])

# Початкові дані
arr = [
    ("LeeKnow", 1, "GroupA"),  # Перший студент
    ("Cristopher", 6, "GroupB"),  # Другий студент
    ("Chanbin", 4, "GroupC")  # Третій студент
]

# Перетворення в масив NumPy
C = np.array(arr, dtype=dt)
print(f"Вихідний масив: \n{C}")

# Додаємо власне ім'я до масиву
my_data = np.array([("MyName", 10, "MyGroup")], dtype=dt)
C = np.append(C, my_data)
print(f"Оновлений масив після додавання вашого імені: \n{C}")

# Збереження в файл
filename = "temp_with_group.csv"
print(f"Записуємо оновлений масив у CSV файл {filename}.")
np.savetxt(filename, C, fmt="%s,%d,%s", header="name,mark,group", delimiter=",")

# Перевіряємо чи файл створився
print(f"Перевіряємо чи файл {filename} створився: {os.listdir()}")

# Зчитування файлу за допомогою NumPy
D = np.genfromtxt(filename, dtype=dt, delimiter=",", skip_header=1)
print(f"Зчитані дані з файлу:\n{D}")

# Доступ до свого імені
my_name_data = D[D['name'] == "MyName"]
if my_name_data.size > 0:
    print(f"Ваші дані у масиві: {my_name_data}")
    print(f"Ваше ім'я: {my_name_data['name'][0]}")
else:
    print("Ваші дані не знайдено в масиві.")



Вихідний масив: 
[('LeeKnow', 1, 'GroupA') ('Cristopher', 6, 'GroupB')
 ('Chanbin', 4, 'GroupC')]
Оновлений масив після додавання вашого імені: 
[('LeeKnow',  1, 'GroupA') ('Cristopher',  6, 'GroupB')
 ('Chanbin',  4, 'GroupC') ('MyName', 10, 'MyGroup')]
Записуємо оновлений масив у CSV файл temp_with_group.csv.
Перевіряємо чи файл temp_with_group.csv створився: ['Chill', 'README.md', 'schmalgauzen.ipynb', 'temp_with_group.csv']
Зчитані дані з файлу:
[('LeeKnow',  1, 'GroupA') ('Cristopher',  6, 'GroupB')
 ('Chanbin',  4, 'GroupC') ('MyName', 10, 'MyGroup')]
Ваші дані у масиві: [('MyName', 10, 'MyGroup')]
Ваше ім'я: MyName


# Операції над масивами

In [21]:


l = (3, 3)

# Створюємо різні матриці
O = np.ones(l)  # Матриця, заповнена 1
R = np.random.random(l)  # Матриця зі випадковими числами [0, 1)
Z = np.zeros(l)  # Матриця, заповнена 0
C = np.arange(l[0])  # Одновимірний масив: [0, 1, 2]

print(f"""
Віднімання (C - (O + 10)):
{C - (O + 10)}


Множення (O * R):
{O * R}


Ділення (R / C):
{np.divide(R, C, out=np.zeros_like(R), where=C!=0)}


Степінь (C ** Z):
{C ** Z}


Порівняння (R > 0.5):
{R > 0.5}


Ділення на 0 (O / Z):
{np.divide(O, Z, out=np.zeros_like(O), where=Z!=0)}

""")

# Завдання:
# 1. Створення матриці eye та перевірка наявності 1.
E = np.eye(3)
print(f"Матриця eye:\n{E}")
print(f"Чи є елементи рівними 1:\n{E == 1}")

# 2. Віднімання матриць ones та eye
ones_matrix = np.ones((3, 3))
result_matrix = ones_matrix - E
print(f"Матриця ones:\n{ones_matrix}")
print(f"Результат (ones - eye):\n{result_matrix}")
print("Як бачимо, центральна діагональ має нулі.")



Віднімання (C - (O + 10)):
[[-11. -10.  -9.]
 [-11. -10.  -9.]
 [-11. -10.  -9.]]


Множення (O * R):
[[0.04004969 0.1121776  0.79270982]
 [0.31817211 0.34302242 0.32371237]
 [0.75747633 0.51095071 0.8736428 ]]


Ділення (R / C):
[[0.         0.1121776  0.39635491]
 [0.         0.34302242 0.16185619]
 [0.         0.51095071 0.4368214 ]]


Степінь (C ** Z):
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


Порівняння (R > 0.5):
[[False False  True]
 [False False False]
 [ True  True  True]]


Ділення на 0 (O / Z):
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Матриця eye:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Чи є елементи рівними 1:
[[ True False False]
 [False  True False]
 [False False  True]]
Матриця ones:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Результат (ones - eye):
[[0. 1. 1.]
 [1. 0. 1.]
 [1. 1. 0.]]
Як бачимо, центральна діагональ має нулі.


# Множення матриць

In [24]:


# Початкові матриці
A = np.array([[1, 2, 3], [2, 2, 2], [3, 3, 3]])
B = np.array([[3, 2, 1], [1, 2, 3], [-1, -2, -3]])

# Множення як матриці
MA = np.asmatrix(A)  # Заміна np.mat на np.asmatrix
MB = np.asmatrix(B)

R = MA * MB
print(f"""
Перетворення масивів A і B на об'єкти класу матриць за допомогою np.asmatrix та їх множення:
{R}
Пояснення: З np.asmatrix масиви A і B перетворюються на матричний формат,
а оператор * виконує матричне множення.
""")



Перетворення масивів A і B на об'єкти класу матриць за допомогою np.asmatrix та їх множення:
[[ 2  0 -2]
 [ 6  4  2]
 [ 9  6  3]]
Пояснення: З np.asmatrix масиви A і B перетворюються на матричний формат,
а оператор * виконує матричне множення.



# Вирівнювання розмірностей

In [26]:
A = np.array([ [11, 12, 13], [21, 22, 23], [31, 32, 33] ])
B = np.array([1, 2, 3])
C = B[:, np.newaxis]

print(f"Вектор В є рядком {B.shape}: {B} тому додавання буде по рядках:\n {A + B}")

print(f"""Вектор C є стовпцем {C.shape}:
{C}
тому додавання буде по стовпцям:
{A + C}""")

print(f"У випадку додавання рядка до стовпця буде матриця в якої доповнюються рядки і стовпці:\n {B + C}")

Вектор В є рядком (3,): [1 2 3] тому додавання буде по рядках:
 [[12 14 16]
 [22 24 26]
 [32 34 36]]
Вектор C є стовпцем (3, 1):
[[1]
 [2]
 [3]]
тому додавання буде по стовпцям:
[[12 13 14]
 [23 24 25]
 [34 35 36]]
У випадку додавання рядка до стовпця буде матриця в якої доповнюються рядки і стовпці:
 [[2 3 4]
 [3 4 5]
 [4 5 6]]


# Конкатенація, повторення та зміна форми (shape)