# Структуровані масиви даних

In [1]:
def homework(message):
    print("\n>>>>>", message, "\n")
import numpy as np


# Визначення однорідного масиву

In [3]:
lst = [ [3.4, 8.7, 9.9], 
        [1.1, -7.8, -0.7],
        [4.1, 12.3, 4.8] ]

# Масив із цілими числами (int8)
A = np.array(lst, dtype=np.int8)
print(f"Отриманий масив має вигляд:\n{repr(A)}")

# Масив із числами у форматі float16
B = np.array(lst, dtype=np.float16)
print(f"Отриманий масив має вигляд:\n{repr(B)}")


Отриманий масив має вигляд:
array([[ 3,  8,  9],
       [ 1, -7,  0],
       [ 4, 12,  4]], dtype=int8)
Отриманий масив має вигляд:
array([[ 3.4,  8.7,  9.9],
       [ 1.1, -7.8, -0.7],
       [ 4.1, 12.3,  4.8]], dtype=float16)


# Задаємо свій тип даних

In [63]:

# Описуємо спеціальний тип даних із полями:
# 'name' — рядок довжиною до 20 символів, 
# 'mark' — цілі числа (int8).
dt = np.dtype([('name', 'U20'), ('mark', np.int8)])  # 'U20' — рядок довжиною до 20 символів.

# Створюємо список даних у форматі кортежів
arr = [
    ("Bohdan", 4),  # Перший студент із оцінкою 4
    ("Marta", 5),   # Другий студент із оцінкою 5
    ("Noname", 0)   # Третій студент із оцінкою 0
]

# Перетворення списку на структурований масив
C = np.array(arr, dtype=dt)

# Вивід масиву
print(f"Отриманий масив має вигляд:\n{C}")

# Доступ до окремої колонки 'mark'
print(f"Доступитись до певної колонки тепер можна за її іменем: {C['mark']}")

# Вивід усіх імен
print(f"Імена всіх студентів у масиві: {C['name']}")


Отриманий масив має вигляд:
[('Bohdan', 4) ('Marta', 5) ('Noname', 0)]
Доступитись до певної колонки тепер можна за її іменем: [4 5 0]
Імена всіх студентів у масиві: ['Bohdan' 'Marta' 'Noname']


# Запис та зчитування з файлу, формат CSV

In [62]:

import os

# Створюємо структуру масиву з додатковим полем 'group'
dt = np.dtype([('name', 'U20'), ('mark', np.int8), ('group', 'U10')])

# Початкові дані
arr = [
    ("LeeKnow", 1, "GroupA"),  # Перший студент
    ("Cristopher", 6, "GroupB"),  # Другий студент
    ("Chanbin", 4, "GroupC")  # Третій студент
]

# Перетворення в масив NumPy
C = np.array(arr, dtype=dt)
print(f"Вихідний масив: \n{C}")

# Додаємо власне ім'я до масиву
my_data = np.array([("MyName", 10, "MyGroup")], dtype=dt)
C = np.append(C, my_data)
print(f"Оновлений масив після додавання вашого імені: \n{C}")

# Збереження в файл
filename = "temp_with_group.csv"
print(f"Записуємо оновлений масив у CSV файл {filename}.")
np.savetxt(filename, C, fmt="%s,%d,%s", header="name,mark,group", delimiter=",")

# Перевіряємо чи файл створився
print(f"Перевіряємо чи файл {filename} створився: {os.listdir()}")

# Зчитування файлу за допомогою NumPy
D = np.genfromtxt(filename, dtype=dt, delimiter=",", skip_header=1)
print(f"Зчитані дані з файлу:\n{D}")

# Доступ до свого імені
my_name_data = D[D['name'] == "MyName"]
if my_name_data.size > 0:
    print(f"Ваші дані у масиві: {my_name_data}")
    print(f"Ваше ім'я: {my_name_data['name'][0]}")
else:
    print("Ваші дані не знайдено в масиві.")



Вихідний масив: 
[('LeeKnow', 1, 'GroupA') ('Cristopher', 6, 'GroupB')
 ('Chanbin', 4, 'GroupC')]
Оновлений масив після додавання вашого імені: 
[('LeeKnow',  1, 'GroupA') ('Cristopher',  6, 'GroupB')
 ('Chanbin',  4, 'GroupC') ('MyName', 10, 'MyGroup')]
Записуємо оновлений масив у CSV файл temp_with_group.csv.
Перевіряємо чи файл temp_with_group.csv створився: ['README.md', 'schmalgauzen.ipynb', 'temp_with_group.csv']
Зчитані дані з файлу:
[('LeeKnow',  1, 'GroupA') ('Cristopher',  6, 'GroupB')
 ('Chanbin',  4, 'GroupC') ('MyName', 10, 'MyGroup')]
Ваші дані у масиві: [('MyName', 10, 'MyGroup')]
Ваше ім'я: MyName


# Операції над масивами

In [21]:


l = (3, 3)

# Створюємо різні матриці
O = np.ones(l)  # Матриця, заповнена 1
R = np.random.random(l)  # Матриця зі випадковими числами [0, 1)
Z = np.zeros(l)  # Матриця, заповнена 0
C = np.arange(l[0])  # Одновимірний масив: [0, 1, 2]

print(f"""
Віднімання (C - (O + 10)):
{C - (O + 10)}


Множення (O * R):
{O * R}


Ділення (R / C):
{np.divide(R, C, out=np.zeros_like(R), where=C!=0)}


Степінь (C ** Z):
{C ** Z}


Порівняння (R > 0.5):
{R > 0.5}


Ділення на 0 (O / Z):
{np.divide(O, Z, out=np.zeros_like(O), where=Z!=0)}

""")

# Завдання:
# 1. Створення матриці eye та перевірка наявності 1.
E = np.eye(3)
print(f"Матриця eye:\n{E}")
print(f"Чи є елементи рівними 1:\n{E == 1}")

# 2. Віднімання матриць ones та eye
ones_matrix = np.ones((3, 3))
result_matrix = ones_matrix - E
print(f"Матриця ones:\n{ones_matrix}")
print(f"Результат (ones - eye):\n{result_matrix}")
print("Як бачимо, центральна діагональ має нулі.")



Віднімання (C - (O + 10)):
[[-11. -10.  -9.]
 [-11. -10.  -9.]
 [-11. -10.  -9.]]


Множення (O * R):
[[0.04004969 0.1121776  0.79270982]
 [0.31817211 0.34302242 0.32371237]
 [0.75747633 0.51095071 0.8736428 ]]


Ділення (R / C):
[[0.         0.1121776  0.39635491]
 [0.         0.34302242 0.16185619]
 [0.         0.51095071 0.4368214 ]]


Степінь (C ** Z):
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


Порівняння (R > 0.5):
[[False False  True]
 [False False False]
 [ True  True  True]]


Ділення на 0 (O / Z):
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Матриця eye:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Чи є елементи рівними 1:
[[ True False False]
 [False  True False]
 [False False  True]]
Матриця ones:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Результат (ones - eye):
[[0. 1. 1.]
 [1. 0. 1.]
 [1. 1. 0.]]
Як бачимо, центральна діагональ має нулі.


# Множення матриць

In [24]:


# Початкові матриці
A = np.array([[1, 2, 3], [2, 2, 2], [3, 3, 3]])
B = np.array([[3, 2, 1], [1, 2, 3], [-1, -2, -3]])

# Множення як матриці
MA = np.asmatrix(A)  # Заміна np.mat на np.asmatrix
MB = np.asmatrix(B)

R = MA * MB
print(f"""
Перетворення масивів A і B на об'єкти класу матриць за допомогою np.asmatrix та їх множення:
{R}
Пояснення: З np.asmatrix масиви A і B перетворюються на матричний формат,
а оператор * виконує матричне множення.
""")



Перетворення масивів A і B на об'єкти класу матриць за допомогою np.asmatrix та їх множення:
[[ 2  0 -2]
 [ 6  4  2]
 [ 9  6  3]]
Пояснення: З np.asmatrix масиви A і B перетворюються на матричний формат,
а оператор * виконує матричне множення.



# Вирівнювання розмірностей

In [26]:
A = np.array([ [11, 12, 13], [21, 22, 23], [31, 32, 33] ])
B = np.array([1, 2, 3])
C = B[:, np.newaxis]

print(f"Вектор В є рядком {B.shape}: {B} тому додавання буде по рядках:\n {A + B}")

print(f"""Вектор C є стовпцем {C.shape}:
{C}
тому додавання буде по стовпцям:
{A + C}""")

print(f"У випадку додавання рядка до стовпця буде матриця в якої доповнюються рядки і стовпці:\n {B + C}")

Вектор В є рядком (3,): [1 2 3] тому додавання буде по рядках:
 [[12 14 16]
 [22 24 26]
 [32 34 36]]
Вектор C є стовпцем (3, 1):
[[1]
 [2]
 [3]]
тому додавання буде по стовпцям:
[[12 13 14]
 [23 24 25]
 [34 35 36]]
У випадку додавання рядка до стовпця буде матриця в якої доповнюються рядки і стовпці:
 [[2 3 4]
 [3 4 5]
 [4 5 6]]


# Конкатенація, повторення та зміна форми (shape)

In [40]:


# 1. Створення масивів
D = np.ones(3)  # Одновимірний масив із трьох одиниць
Z = np.zeros((3, 1))  # Двовимірний масив (3 рядки, 1 стовпець) із нулів

# 2. Конкатенація рядків
print(f"""
При конкатенації рядків маємо: {np.concatenate((D, D))} 
# D - це одновимірний масив, тому об'єднання дає результат [1. 1. 1. 1. 1. 1.]
""")

# 3. Конкатенація стовпців
print(f"""
При конкатенації стовпців маємо:\n{np.concatenate((Z, Z), axis=1)} 
# Z - це двовимірний масив, об'єднання відбувається по другій осі (стовпцях), даючи масив з нулями у двох стовпцях.
""")

# 4. Масив D має розмірність (3,), тому не може виконати пряму конкатенацію з B, якщо B має іншу розмірність.
B = np.zeros((3, 1))  # Масив із трьох нулів (3 рядки, 1 стовпець)
print(f"""
Масив D {D} має розмірність {D.shape} тому може виконати операцію конкатенації з B {B} розмірністю {B.shape}:
{np.concatenate((B, D[:, np.newaxis]))}
# Щоб об'єднати масиви, D потрібно перетворити в масив із розмірністю (3, 1) за допомогою D[:, np.newaxis] або D.reshape((3,1)).
""")

# 5. Конкатенація з іншим масивом C
C = np.arange(3).reshape(3, 1)  # Масив [[0], [1], [2]]
print(f"""
Для конкатенації з C
{C}
де C має розмірність = {C.shape} потрібно змінити розмірність D = {D.shape}
Це можна ось так:
{D[:, np.newaxis].shape}
або
{D.reshape((3,1)).shape}
в результаті ми можемо виконати конкатенацію:
{np.concatenate((C, D.reshape((3, 1))), axis=1)}
""")

# 6. Повторення масиву D
print(f"""
При повторенні D {D} 2 рази для рядків та 3 рази для стовпців будемо мати:
{np.tile(D, (2, 3))}
# Повторення створює масив, у якому D дублюється по рядках і стовпцях.
""")

# 7. Відмінності між конкатенацією та повторенням
print(f"""
Як бачимо, конкатенація та повторення є дещо схожими у деяких випадках:
- конкатенація: {np.concatenate((D, D))}
- повторення: {np.tile(D, 2)}
# Конкатенація додає нові елементи до кінця, а повторення дублює існуючі.
""")

# 8. Перетворення двовимірного масиву A на рядок
A = np.arange(12).reshape(3, 4)  # Масив 3x4
print(f"""
Також можна перетворити двовимірний масив A розмірністю {A.shape} на рядок: {A.flatten()} з розмірністю {A.flatten().shape}
# Метод flatten() перетворює будь-який багатовимірний масив в одновимірний.
""")



При конкатенації рядків маємо: [1. 1. 1. 1. 1. 1.] 
# D - це одновимірний масив, тому об'єднання дає результат [1. 1. 1. 1. 1. 1.]


При конкатенації стовпців маємо:
[[0. 0.]
 [0. 0.]
 [0. 0.]] 
# Z - це двовимірний масив, об'єднання відбувається по другій осі (стовпцях), даючи масив з нулями у двох стовпцях.


Масив D [1. 1. 1.] має розмірність (3,) тому може виконати операцію конкатенації з B [[0.]
 [0.]
 [0.]] розмірністю (3, 1):
[[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]]
# Щоб об'єднати масиви, D потрібно перетворити в масив із розмірністю (3, 1) за допомогою D[:, np.newaxis] або D.reshape((3,1)).


Для конкатенації з C
[[0]
 [1]
 [2]]
де C має розмірність = (3, 1) потрібно змінити розмірність D = (3,)
Це можна ось так:
(3, 1)
або
(3, 1)
в результаті ми можемо виконати конкатенацію:
[[0. 1.]
 [1. 1.]
 [2. 1.]]


При повторенні D [1. 1. 1.] 2 рази для рядків та 3 рази для стовпців будемо мати:
[[1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]]
# Повторення створює масив, у яком

## Створіть двовимірний масив за допомогою arange та виконайте конкатенацію та повторення.


In [7]:
X = np.arange(6).reshape(2, 3)  # Масив 2x3
Y = np.arange(3, 9).reshape(2, 3)  # Ще один масив 2x3

print(f"Конкатенація масивів по рядках:\n{np.concatenate((X, Y), axis=0)}")
print(f"Конкатенація масивів по стовпцях:\n{np.concatenate((X, Y), axis=1)}")
print(f"Повторення масиву X 2 рази:\n{np.tile(X, (2, 1))}")


Конкатенація масивів по рядках:
[[0 1 2]
 [3 4 5]
 [3 4 5]
 [6 7 8]]
Конкатенація масивів по стовпцях:
[[0 1 2 3 4 5]
 [3 4 5 6 7 8]]
Повторення масиву X 2 рази:
[[0 1 2]
 [3 4 5]
 [0 1 2]
 [3 4 5]]


## Спробуйте виконати конкатенацію масивів із різною кількістю рядків і стовпців.

In [10]:
P = np.arange(4).reshape(2, 2)  # Масив 2x2
Q = np.arange(6).reshape(3, 2)  # Масив 3x2

# Конкатенація неможлива без зміни розмірностей
P_resized = np.resize(P, (3, 2))  # Зміна розміру P до 3x2
print(f"Конкатенація P та Q після зміни розмірності P:\n{np.concatenate((P_resized, Q), axis=0)}")


Конкатенація P та Q після зміни розмірності P:
[[0 1]
 [2 3]
 [0 1]
 [0 1]
 [2 3]
 [4 5]]


## Знайдіть усі можливі комбінації reshape для масиву з розмірністю 12.

In [11]:
array = np.arange(12)

shapes = [(1, 12), (12, 1), (2, 6), (6, 2), (3, 4), (4, 3)]
for shape in shapes:
    print(f"Масив {shape}:\n{array.reshape(shape)}\n")

Масив (1, 12):
[[ 0  1  2  3  4  5  6  7  8  9 10 11]]

Масив (12, 1):
[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]]

Масив (2, 6):
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]

Масив (6, 2):
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]

Масив (3, 4):
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Масив (4, 3):
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]



# Трансформації масивів

In [39]:


# Початковий масив O
O = np.arange(6).reshape(3, 2)  # Масив 3x2 із чисел [0, 1, 2, 3, 4, 5]
O_r = O.reshape((2, 3))  # Зміна форми на 2x3
O_f = O.flatten()  # Перетворення у вектор (одновимірний масив)
O_t = O.transpose()  # Транспонування, змінює місцями рядки та стовпці
O_fl = np.flip(O)  # Обертання масиву (дзеркальне відображення по обох осях)
O_fa = np.flip(O, axis=1)  # Дзеркальне відображення лише по горизонталі (стовпцях)

# Вивід результатів із поясненнями
print(f"""
Початковий масив O:
{O}

Змінити розмірність shape {O.shape} на {O_r.shape} (3x2 → 2x3).
Розмір масиву size {O.size} однаковий, оскільки кількість елементів не змінюється, а кількість вимірів ndim {np.ndim(O)} = {np.ndim(O_r)} теж залишається незмінною:
{O_r}

Також можна перетворити {np.ndim(O)}-вимірний масив розмірністю {O.shape} на рядок (одновимірний масив):
{O_f}
Цей вектор має розмірність {O_f.shape}, кількість елементів size = {O_f.size}, а вимірність ndim стала {np.ndim(O_f)}-вимірною.

Транспонування масиву змінює його форму з {O.shape} на {O_t.shape} (рядки стають стовпцями):
{O_t}

Обертання масиву (дзеркальне відображення по рядках і стовпцях одночасно):
{O_fl}

Дзеркальне відображення лише по стовпцях (елементи в кожному рядку відображаються):
{O_fa}
""")



Початковий масив O:
[[0 1]
 [2 3]
 [4 5]]

Змінити розмірність shape (3, 2) на (2, 3) (3x2 → 2x3).
Розмір масиву size 6 однаковий, оскільки кількість елементів не змінюється, а кількість вимірів ndim 2 = 2 теж залишається незмінною:
[[0 1 2]
 [3 4 5]]

Також можна перетворити 2-вимірний масив розмірністю (3, 2) на рядок (одновимірний масив):
[0 1 2 3 4 5]
Цей вектор має розмірність (6,), кількість елементів size = 6, а вимірність ndim стала 1-вимірною.

Транспонування масиву змінює його форму з (3, 2) на (2, 3) (рядки стають стовпцями):
[[0 2 4]
 [1 3 5]]

Обертання масиву (дзеркальне відображення по рядках і стовпцях одночасно):
[[5 4]
 [3 2]
 [1 0]]

Дзеркальне відображення лише по стовпцях (елементи в кожному рядку відображаються):
[[1 0]
 [3 2]
 [5 4]]



## Створіть вектор із 12 елементів, визначте його shape, size та ndim.

In [23]:
vector = np.arange(12)  # Вектор із 12 елементів [0, 1, ..., 11]
print(f"Вектор: {vector}")
print(f"Shape: {vector.shape}, Size: {vector.size}, Ndim: {vector.ndim}")


Вектор: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Shape: (12,), Size: 12, Ndim: 1


## Змініть розмірність, перетворивши вектор у матрицю.

In [26]:
matrix = vector.reshape(3, 4)  # Матриця 3x4
print(f"Матриця:\n{matrix}")
print(f"Shape: {matrix.shape}, Size: {matrix.size}, Ndim: {matrix.ndim}")


Матриця:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Shape: (3, 4), Size: 12, Ndim: 2


## Здійсніть транспонування отриманої матриці та оберніть її.

In [34]:
matrix_t = matrix.transpose()  # Транспонована матриця 4x3
print(f"Транспонована матриця:\n{matrix_t}")
matrix_flipped = np.flip(matrix_t)  # Дзеркальне обертання
print(f"Обернута матриця:\n{matrix_flipped}")


Транспонована матриця:
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
Обернута матриця:
[[11  7  3]
 [10  6  2]
 [ 9  5  1]
 [ 8  4  0]]


## Перетворіть отриманий багатовимірний масив назад у вектор.

In [38]:
flattened = matrix_flipped.flatten()  # Одновимірний масив
print(f"Перетворений у вектор:\n{flattened}")
print(f"Shape: {flattened.shape}, Size: {flattened.size}, Ndim: {flattened.ndim}")


Перетворений у вектор:
[11  7  3 10  6  2  9  5  1  8  4  0]
Shape: (12,), Size: 12, Ndim: 1


# Генерація випадкових масивів та статистичні закони розподілу

In [61]:


# Початковий масив
C = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

print(f"""
Масив {C.shape} можна задавати вручну, вказуючи елементи:
{C}
# Це масив 3x4, елементи задані явно через список списків.
""")

# Генерація випадкового масиву без фіксованого seed
rng = np.random.default_rng()
C = rng.random((3, 4))
print(f"""
Можна згенерувати випадковий масив такої ж розмірності {C.shape}:
{C}
# Використовуємо генератор `rng.random((3, 4))`, який створює випадкові числа в інтервалі [0, 1) для масиву розмірності 3x4.
""")

# Генерація випадкового масиву з фіксованим seed
rng = np.random.default_rng(seed=10)
C = rng.random((3, 4))
print(f"""
Для того щоб згенерований масив {C.shape} завжди мав однакові значення, використовуємо параметр `seed`:
{C}
# Фіксування `seed=10` гарантує, що результат генерації завжди буде однаковим, незалежно від кількості запусків.
""")

# Генерація масиву з цілих чисел
I = rng.integers(0, 10, size=(3, 4), endpoint=True)
print(f"""
Можемо створювати масиви цілих чисел, задаючи мінімум і максимум:
{I}
# Функція `rng.integers(0, 10, size=(3, 4), endpoint=True)` створює масив 3x4 із випадкових цілих чисел у межах [0, 10], включаючи 10 (через `endpoint=True`).
""")



Масив (3, 4) можна задавати вручну, вказуючи елементи:
[[0.45053314 0.17296777 0.34376245 0.5510652 ]
 [0.54627315 0.05093587 0.40067661 0.55645993]
 [0.12697628 0.82485143 0.26590556 0.56917101]]
# Це масив 3x4, елементи задані явно через список списків.


Можна згенерувати випадковий масив такої ж розмірності (3, 4):
[[0.91904566 0.52448489 0.73481475 0.67241547]
 [0.19562153 0.83136328 0.62860597 0.77358485]
 [0.73712249 0.17366768 0.73781641 0.58943368]]
# Використовуємо генератор `rng.random((3, 4))`, який створює випадкові числа в інтервалі [0, 1) для масиву розмірності 3x4.


Для того щоб згенерований масив (3, 4) завжди мав однакові значення, використовуємо параметр `seed`:
[[0.95600171 0.20768181 0.82844489 0.14928212]
 [0.51280462 0.1359196  0.68903648 0.84174772]
 [0.425509   0.956926   0.82533291 0.33821531]]
# Фіксування `seed=10` гарантує, що результат генерації завжди буде однаковим, незалежно від кількості запусків.


Можемо створювати масиви цілих чисел, задаючи мінім

## Створіть масив випадкових чисел із плаваючою точкою (5 рядків, 3 стовпці).

In [46]:
rng = np.random.default_rng()
A = rng.random((5, 3))  # Масив 5x3 із чисел в інтервалі [0, 1)
print(f"Випадковий масив 5x3:\n{A}")


Випадковий масив 5x3:
[[0.06955526 0.75470146 0.76579849]
 [0.97814177 0.95657641 0.60779747]
 [0.13623918 0.74750977 0.18227357]
 [0.55806716 0.94207703 0.18843853]
 [0.7730231  0.67080336 0.34147869]]


## Створіть масив цілих чисел (4 рядки, 4 стовпці) із діапазоном значень від -5 до 5.

In [49]:
B = rng.integers(-5, 5, size=(4, 4))
print(f"Масив із цілих чисел (-5 до 5):\n{B}")


Масив із цілих чисел (-5 до 5):
[[-5 -5 -4 -4]
 [ 3  1 -1 -3]
 [ 2  1 -5 -4]
 [-4  4  1  3]]


## Згенеруйте випадковий масив розміром 3x3 із фіксованим seed і перевірте, чи однакові результати при повторному запуску.

In [52]:
rng = np.random.default_rng(seed=42)
C = rng.random((3, 3))  # Масив 3x3 із фіксованим seed
print(f"Фіксований seed, масив 3x3:\n{C}")


Фіксований seed, масив 3x3:
[[0.77395605 0.43887844 0.85859792]
 [0.69736803 0.09417735 0.97562235]
 [0.7611397  0.78606431 0.12811363]]


## Згенеруйте масив розміром 2x6 із цілих чисел, у якому максимальне значення включено до результату.

In [60]:
D = rng.integers(0, 10, size=(2, 6), endpoint=True)
print(f"Масив із endpoint=True (максимальне значення включено):\n{D}")


Масив із endpoint=True (максимальне значення включено):
[[8 0 8 8 8 7]
 [5 7 3 8 6 5]]


# Величини які характеризують множину чисел

In [68]:
import numpy as np

# Початковий масив
C = np.array([1, 2, 5, 8, 9, 10])  # Масив для прикладу розрахунків

print(f"""
Працюємо з початковим одновимірним масивом:
{C}

Сума всіх елементів:    {C.sum()} 
# Сума чисел масиву: 1 + 2 + 5 + 8 + 9 + 10 = {C.sum()}.

Добуток всіх елементів: {C.prod()} 
# Добуток чисел масиву: 1 * 2 * 5 * 8 * 9 * 10 = {C.prod()}.

Мінімальний елемент:    {C.min()} 
# Найменше значення в масиві: {C.min()}.

Максимальний елемент:   {C.max()} 
# Найбільше значення в масиві: {C.max()}.

Середнє значення:       {C.mean()}  
# Середнє арифметичне: сума чисел {C.sum()} поділена на кількість елементів {np.size(C)}.

Медіана:                {np.median(C)} 
# Медіана - центральне значення в упорядкованому масиві (для парної кількості - середнє двох центральних).

Дисперсія:              {C.var()}   
# Вимірювання розсіювання даних навколо середнього: сума квадратів відхилень поділена на кількість елементів.

Відхилення:             {C.std()}   
# Стандартне відхилення: квадратний корінь із дисперсії {np.sqrt(C.var())}.

Заокруглили всі значення:
{np.round(C)} 
# Для цього масиву заокруглення не змінює значень.

Унікальні значення після заокруглення: {np.unique(np.round(C))}
# Пошук унікальних значень, що залишаються після заокруглення.

Кількість кожного унікального значення: {np.unique(np.round(C), return_counts=True)[1]}
# Для кожного унікального значення визначаємо, скільки разів воно зустрічається в масиві.
""")

# Перетворення на двовимірний масив
C = C.reshape(2, 3)  # Масив 2x3
print(f"""
Двовимірний масив:
{C}

Сума елементів по стовпцях:         {C.sum(axis=0)} 
# Сума для кожного стовпця окремо: [1+8, 2+9, 5+10].

Сума елементів по рядках:          {C.sum(axis=1)} 
# Сума для кожного рядка окремо: [1+2+5, 8+9+10].

Добуток елементів по стовпцях:      {C.prod(axis=0)} 
# Добуток для кожного стовпця окремо: [1*8, 2*9, 5*10].

Добуток елементів по рядках:        {C.prod(axis=1)} 
# Добуток для кожного рядка окремо: [1*2*5, 8*9*10].

Мінімальний елемент по стовпцях:    {C.min(axis=0)} 
# Найменше значення в кожному стовпці.

Мінімальний елемент по рядках:      {C.min(axis=1)} 
# Найменше значення в кожному рядку.

Максимальний елемент по стовпцях:   {C.max(axis=0)} 
# Найбільше значення в кожному стовпці.

Максимальний елемент по рядках:     {C.max(axis=1)} 
# Найбільше значення в кожному рядку.

Середнє значення по стовпцях:       {C.mean(axis=0)} 
# Середнє значення для кожного стовпця.

Дисперсія по стовпцях:              {C.var(axis=0)} 
# Дисперсія для кожного стовпця.

Відхилення по стовпцях:             {C.std(axis=0)} 
# Стандартне відхилення для кожного стовпця.
""")



Працюємо з початковим одновимірним масивом:
[ 1  2  5  8  9 10]

Сума всіх елементів:    35 
# Сума чисел масиву: 1 + 2 + 5 + 8 + 9 + 10 = 35.

Добуток всіх елементів: 7200 
# Добуток чисел масиву: 1 * 2 * 5 * 8 * 9 * 10 = 7200.

Мінімальний елемент:    1 
# Найменше значення в масиві: 1.

Максимальний елемент:   10 
# Найбільше значення в масиві: 10.

Середнє значення:       5.833333333333333  
# Середнє арифметичне: сума чисел 35 поділена на кількість елементів 6.

Медіана:                6.5 
# Медіана - центральне значення в упорядкованому масиві (для парної кількості - середнє двох центральних).

Дисперсія:              11.805555555555555   
# Вимірювання розсіювання даних навколо середнього: сума квадратів відхилень поділена на кількість елементів.

Відхилення:             3.435921354681384   
# Стандартне відхилення: квадратний корінь із дисперсії 3.435921354681384.

Заокруглили всі значення:
[ 1  2  5  8  9 10] 
# Для цього масиву заокруглення не змінює значень.

Унікальні зна