# Робота з бібліотекою Numpy




In [12]:

%pip install numpy
def homework(message):
    print("\n>>>>>", message, "\n")


import numpy as np

# Створюємо список температур
temperature = [20.1, 20.1, 20.2, 20.4]
print(f"Оригінальний список temperature: {temperature}")


# Множимо список на 5
t1 = temperature * 5
print(f"При множенні списку temperature на 5 маємо дублювання елементів: {t1}")

homework("Чому маємо такий результат?")
homework( """У Python множення списку на число дублює список,
    а не множить його елементи. Тому результатом є новий список 
    із повторенням елементів початкового списку.?""")

# Множимо кожен елемент списку на 5 за допомогою list comprehension
t1 = [x * 5 for x in temperature]
print(f"Тепер кожен елемент списку множиться на 5: {t1}")

homework("Чому тепер множення успішне?")
homework("""Спискове включення (list comprehension) ітеративно проходить
          кожен елемент списку та виконує над ним арифметичну операцію.
          Таким чином, кожен елемент множиться на 5, і створюється новий список.""")


# Конвертуємо список temperature у NumPy-масив
t2 = np.array(temperature)
print(f"Конвертація списку temperature у NumPy-масив: {t2}")


# Множимо NumPy-масив на 5
t3 = t2 * 5
print(f"При множенні NumPy-масиву на 5 отримуємо: {t3}")



Note: you may need to restart the kernel to use updated packages.
Оригінальний список temperature: [20.1, 20.1, 20.2, 20.4]
При множенні списку temperature на 5 маємо дублювання елементів: [20.1, 20.1, 20.2, 20.4, 20.1, 20.1, 20.2, 20.4, 20.1, 20.1, 20.2, 20.4, 20.1, 20.1, 20.2, 20.4, 20.1, 20.1, 20.2, 20.4]

>>>>> Чому маємо такий результат? 


>>>>> У Python множення списку на число дублює список,
    а не множить його елементи. Тому результатом є новий список 
    із повторенням елементів початкового списку.? 

Тепер кожен елемент списку множиться на 5: [100.5, 100.5, 101.0, 102.0]

>>>>> Чому тепер множення успішне? 


>>>>> Спискове включення (list comprehension) ітеративно проходить
          кожен елемент списку та виконує над ним арифметичну операцію.
          Таким чином, кожен елемент множиться на 5, і створюється новий список. 

Конвертація списку temperature у NumPy-масив: [20.1 20.1 20.2 20.4]
При множенні NumPy-масиву на 5 отримуємо: [100.5 100.5 101.  102. ]


# Вектори, створення та робота з ними

In [16]:

print("Все можна створити вручну за допомогою методу np.array, передавши йому набір значень у вигляді List:")

# Створюємо рядковий вектор
vector_row = np.array([[1, -5, 3, 2, 4]])
print(f"Рядковий вектор (1 рядок, 5 колонок): {vector_row}")  
print(f"Розмір вектора: {vector_row.shape}")
# Пояснення: Масив `vector_row` містить 1 рядок і 5 елементів (стовпчиків).
# `shape` повертає розмір масиву: (1, 5), що означає 1 рядок і 5 колонок.

# Створюємо стовпчиковий вектор
vector_column = np.array([[1], 
                          [2], 
                          [3], 
                          [4]])
print(f"\nСтовпчиковий вектор (4 рядки, 1 колонка):\n{vector_column}")
print(f"Розмір вектора: {vector_column.shape}")
# Пояснення: Масив `vector_column` містить 4 рядки і 1 колонку.
# `shape` повертає розмір масиву: (4, 1), що означає 4 рядки і 1 колонка.





Все можна створити вручну за допомогою методу np.array, передавши йому набір значень у вигляді List:
Рядковий вектор (1 рядок, 5 колонок): [[ 1 -5  3  2  4]]
Розмір вектора: (1, 5)

Стовпчиковий вектор (4 рядки, 1 колонка):
[[1]
 [2]
 [3]
 [4]]
Розмір вектора: (4, 1)


# Метод arange 

In [18]:
# Початкові значення
start = 5
size_of_vec = 100

# Генерація діапазонів
x = range(size_of_vec)
a = np.arange(size_of_vec)
print(f"Масив згенерований простим range: {list(x)[0:5]} та методом arange: {a[0:5]}")
print(">>> Виведено перші п'ять елементів обох масивів. Range повертає об'єкт і потрібно обгорнути в list для перегляду.")

# Завдання
print(">>>>> Виведіть весь діапазон чисел.")
print(f"Весь діапазон range: {list(x)}")
print(f"Весь діапазон arange: {a}")

# Генерація з заданим початком
a = np.arange(start, size_of_vec)
print(f"Можемо задавати початок генерації вектора, перший елемент: {a[0]}")
print(">>> Початок вектора задається параметром 'start'. У цьому випадку перший елемент масиву дорівнює 5.")

# Завдання
print(">>>>> Виведіть останній діапазон в згенерованому масиві.")
print(f"Останні п'ять елементів: {a[-5:]}")

# Діапазон через функцію range
x = range(start, size_of_vec)
print("Те саме, але з вбудованою функцією range:", list(x))
print("Власне вивід значень:", list(x)[0])
print(">>> З range результат ідентичний, але це вбудована функція Python, яка працює для цілих чисел.")

# Завдання
print(">>>>> Виведіть якесь число з середини діапазону.")
print(f"Число з середини: {list(x)[len(x) // 2]}")

# Дробові числа
x = np.arange(10.4)
print("Будем мати:", x)
print(">>> Масив генерується до вказаного значення 10.4, але останній елемент менший за 10.4, бо np.arange генерує діапазон [start, stop).")

# Крок 0.5
x = np.arange(0.5, 4, 0.5)
print("З кроком 0.5:", x)
print(">>> Крок визначає різницю між сусідніми значеннями. Тут масив генерується від 0.5 до 4 (виключно) з кроком 0.5.")

# Крок 0.08
x = np.arange(0.04, 1.84, 0.08)
print("З кроком 0.08:", x, "\nЗверніть увагу на заокруглення")
print(">>> Числа у float можуть мати похибки через спосіб зберігання чисел з плаваючою комою.")

# Завдання
print(">>>>> Згенеруйте значення, де крок буде мати чотири нулі після коми, яким буде результат?")
x = np.arange(0.0001, 0.001, 0.0001)
print(f"З кроком 0.0001: {x}")
print(">>> Отримали значення з точністю до чотирьох знаків після коми. Переконайтесь, що у результатах немає пропущених значень через похибку.")

# Множення
y = x * 2.5
print("Після перемноження:", y)
print(">>> Кожне значення масиву множиться на 2.5.")

# Завдання
print(">>>>> Піднесіть отримане число до степеня та поділіть на 0.4 - Яким буде результат?")
z = (y ** 2) / 0.4
print(f"Результат: {z}")
print(">>> Кожне значення масиву піднесено до квадрату (y^2) і потім поділено на 0.4.")


Масив згенерований простим range: [0, 1, 2, 3, 4] та методом arange: [0 1 2 3 4]
>>> Виведено перші п'ять елементів обох масивів. Range повертає об'єкт і потрібно обгорнути в list для перегляду.
>>>>> Виведіть весь діапазон чисел.
Весь діапазон range: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]
Весь діапазон arange: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
Можемо задавати початок генер

# Метод linspace

In [25]:
start = 5
size_of_vec = 100

# Генерація чисел за допомогою np.linspace
a = np.linspace(start, size_of_vec)
print(f"Згенерували {len(a)} чисел в діапазоні від {a[0]} до {a[-1]}")
print(">>> За замовчуванням linspace генерує 50 чисел, рівномірно розподілених між start і size_of_vec.")

# Завдання
print(">>>>> Виведіть кожне друге число згенерованого діапазону. Тут буде потрібен цикл :)")
for i in range(1, len(a), 2):
    print(f"Кожне друге число: {a[i]}")

# Зменшення кількості чисел
print("Можна зменшити кількість чисел до 5:")
a = np.linspace(start, size_of_vec, 5)
print(a)
print(">>> Тут генерується 5 чисел, включаючи початкове (start) і кінцеве (size_of_vec), з рівними інтервалами.")

# Завдання
print(">>>>> Збільшіть кількість чисел до 100. Виведіть перших та останніх 10.")
a = np.linspace(start, size_of_vec, 100)
print(f"Перші 10 чисел: {a[:10]}")
print(f"Останні 10 чисел: {a[-10:]}")

# Врахування крайніх значень
print("""Як бачимо перше та останнє значення завжди входять у згенерований діапазон. 
Відповідно при цьому вираховується крок.
Це можна змінити, виключивши останнє значення з визначення діапазону.""")

# Виключення останнього значення
a = np.linspace(start, size_of_vec, 5, endpoint=False)
print(a)
print(">>> Виключення endpoint змінює поведінку: останнє число не входить у масив.")

# Завдання
print(">>>>> Спробуйте самі порахувати крок.")
manual_step = (size_of_vec - start) / 5
print(f"Ручний розрахунок кроку (endpoint=False): {manual_step}")

# Порівняння автоматичних кроків
_, sp_1 = np.linspace(start, size_of_vec, 5, endpoint=True, retstep=True)
_, sp_2 = np.linspace(start, size_of_vec, 5, endpoint=False, retstep=True)
print(f"Для порівняння, ми можемо визначити крок автоматично, у нашому випадку це {sp_1} (endpoint=True) та {sp_2} (endpoint=False)")
print(">>> Автоматичний розрахунок кроку залежить від включення або виключення останнього значення.")




Згенерували 50 чисел в діапазоні від 5.0 до 100.0
>>> За замовчуванням linspace генерує 50 чисел, рівномірно розподілених між start і size_of_vec.
>>>>> Виведіть кожне друге число згенерованого діапазону. Тут буде потрібен цикл :)
Кожне друге число: 6.938775510204081
Кожне друге число: 10.816326530612244
Кожне друге число: 14.693877551020408
Кожне друге число: 18.57142857142857
Кожне друге число: 22.448979591836736
Кожне друге число: 26.3265306122449
Кожне друге число: 30.20408163265306
Кожне друге число: 34.08163265306122
Кожне друге число: 37.95918367346939
Кожне друге число: 41.83673469387755
Кожне друге число: 45.714285714285715
Кожне друге число: 49.59183673469388
Кожне друге число: 53.46938775510204
Кожне друге число: 57.3469387755102
Кожне друге число: 61.224489795918366
Кожне друге число: 65.10204081632654
Кожне друге число: 68.9795918367347
Кожне друге число: 72.85714285714286
Кожне друге число: 76.73469387755102
Кожне друге число: 80.61224489795919
Кожне друге число: 84.48979

# Типи масивів/векторів

In [40]:

# Приклади для аналізу
examples = {
    'Скаляр': np.array(1), 
    'Вектор Рядок': np.array([1, 2, 3]), 
    'Вектор Стовпець': np.array([[1], [2], [3]]), 
    'Матриця': np.array([[1, 2],[3, 4], [5, 6]]),
    'Багатовимірна Матриця': np.array([ [[111, 112], [121, 122]],
                                        [[211, 212], [221, 222]],
                                        [[311, 312], [321, 322]] ])
}

# Аналіз кожного прикладу
for key, value in examples.items():
    print(f"Розглядаємо приклад з {key}. \nЗначення x буде: \n{value}")
    print(f"Тип {key} x: {type(value)}")
    print(f"Розмірність/вимір {key} x (ndim): {np.ndim(value)}")
    print(f"Форма {key} x (shape): {value.shape}")
    print(f"Кількість елементів {key} x (size): {np.size(value)}")
    print(">>> Пояснення:")
    print(f"- `np.ndim` показує кількість вимірів: {np.ndim(value)}. Наприклад, для скаляра це 0 (немає вимірів), для вектора рядка це 1, а для багатовимірної матриці — 3.")
    print(f"- `shape` описує кількість елементів у кожному вимірі. Наприклад, форма скаляра — порожній кортеж (), а форма матриці — (рядки, стовпці).")
    print(f"- Вектори можуть мати різну форму, але їхня розмірність (ndim) все одно буде 1 (рядок) або 2 (стовпець).")
    print("-=-" * 10)

# Завдання
print(">>>>> Як Ви думаєте чому маємо такий результат для функції np.ndim?")
print("""
`np.ndim` повертає кількість вимірів у масиві. Для вектора рядка (наприклад, [1, 2, 3]) це один вимір (ndim=1), 
оскільки елементи розташовані в одній послідовності. 
Для вектора-стовпця ([[1], [2], [3]]) вимірів уже два (ndim=2), бо це матриця з одним стовпцем і кількома рядками. 
`shape` повертає кількість елементів у кожному вимірі, тому значення можуть не співпадати з ndim.""")

print(">>>>> Задайте власні вектори з різними числами.")

# Власні приклади
vector_row = np.array([10, 20, 30, 40])
vector_column = np.array([[100], [200], [300], [400]])
matrix = np.array([[1, 2, 3], [4, 5, 6]])
tensor = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print("Мій Вектор Рядок:")
print(f"Значення: {vector_row}")
print(f"Розмірність: {np.ndim(vector_row)}, Форма: {vector_row.shape}, Кількість елементів: {np.size(vector_row)}")

print("Мій Вектор Стовпець:")
print(f"Значення: \n{vector_column}")
print(f"Розмірність: {np.ndim(vector_column)}, Форма: {vector_column.shape}, Кількість елементів: {np.size(vector_column)}")

print("Моя Матриця:")
print(f"Значення: \n{matrix}")
print(f"Розмірність: {np.ndim(matrix)}, Форма: {matrix.shape}, Кількість елементів: {np.size(matrix)}")

print("Моя Багатовимірна Матриця (Тензор):")
print(f"Значення: \n{tensor}")
print(f"Розмірність: {np.ndim(tensor)}, Форма: {tensor.shape}, Кількість елементів: {np.size(tensor)}")


Розглядаємо приклад з Скаляр. 
Значення x буде: 
1
Тип Скаляр x: <class 'numpy.ndarray'>
Розмірність/вимір Скаляр x (ndim): 0
Форма Скаляр x (shape): ()
Кількість елементів Скаляр x (size): 1
>>> Пояснення:
- `np.ndim` показує кількість вимірів: 0. Наприклад, для скаляра це 0 (немає вимірів), для вектора рядка це 1, а для багатовимірної матриці — 3.
- `shape` описує кількість елементів у кожному вимірі. Наприклад, форма скаляра — порожній кортеж (), а форма матриці — (рядки, стовпці).
- Вектори можуть мати різну форму, але їхня розмірність (ndim) все одно буде 1 (рядок) або 2 (стовпець).
-=--=--=--=--=--=--=--=--=--=-
Розглядаємо приклад з Вектор Рядок. 
Значення x буде: 
[1 2 3]
Тип Вектор Рядок x: <class 'numpy.ndarray'>
Розмірність/вимір Вектор Рядок x (ndim): 1
Форма Вектор Рядок x (shape): (3,)
Кількість елементів Вектор Рядок x (size): 3
>>> Пояснення:
- `np.ndim` показує кількість вимірів: 1. Наприклад, для скаляра це 0 (немає вимірів), для вектора рядка це 1, а для багатовимірн

# Багатовимірні масиви, розуміння вимірів

In [56]:


# Приклади масивів
examples = {
    '5 рядків': np.array([[1], [2], [3], [4], [5]]),  # Матриця з 5 рядків і 1 стовпця
    '5 стовпців': np.array([[1, 2, 3, 4, 5]]),       # Матриця з 1 рядка і 5 стовпців
    '5 елементів': np.array([[[1, 2, 3, 4, 5]]])     # Тензор розмірності (1, 1, 5)
}

# Аналіз кожного прикладу
for key, value in examples.items():
    print(f"Для {key} маємо shape: {value.shape}")
    print(f"Вигляд масиву: \n{value}")
    print(">>> Пояснення:")
    if len(value.shape) == 2:
        print(f"- Це двовимірний масив (матриця). Форма показує кількість рядків і стовпців: {value.shape}.")
    elif len(value.shape) == 3:
        print(f"- Це тривимірний масив (тензор). Форма показує кількість блоків, рядків і стовпців: {value.shape}.")
    print("-=-" * 10)

# Завдання: створення власних масивів
print(">>>>> Створіть власні масиви з різною кількістю елементів та використайте метод shape для визначення їх вимірів.")

# Власні приклади
my_array_1 = np.array([10, 20, 30])          # Одновимірний масив (вектор)
my_array_2 = np.array([[1, 2], [3, 4]])      # Матриця 2x2
my_array_3 = np.array([[[1, 2]], [[3, 4]]])  # Тривимірний масив (2 блоки по 1x2)

# Аналіз власних масивів
print("Масив 1 (вектор):")
print(f"Значення: {my_array_1}")
print(f"Форма (shape): {my_array_1.shape}")
print(">>> Одновимірний масив, форма показує кількість елементів у ньому.")

print("\nМасив 2 (матриця):")
print(f"Значення: \n{my_array_2}")
print(f"Форма (shape): {my_array_2.shape}")
print(">>> Двовимірний масив (матриця), форма показує кількість рядків і стовпців.")

print("\nМасив 3 (тензор):")
print(f"Значення: \n{my_array_3}")
print(f"Форма (shape): {my_array_3.shape}")
print(">>> Тривимірний масив, форма показує кількість блоків, рядків і стовпців у кожному блоці.")


Для 5 рядків маємо shape: (5, 1)
Вигляд масиву: 
[[1]
 [2]
 [3]
 [4]
 [5]]
>>> Пояснення:
- Це двовимірний масив (матриця). Форма показує кількість рядків і стовпців: (5, 1).
-=--=--=--=--=--=--=--=--=--=-
Для 5 стовпців маємо shape: (1, 5)
Вигляд масиву: 
[[1 2 3 4 5]]
>>> Пояснення:
- Це двовимірний масив (матриця). Форма показує кількість рядків і стовпців: (1, 5).
-=--=--=--=--=--=--=--=--=--=-
Для 5 елементів маємо shape: (1, 1, 5)
Вигляд масиву: 
[[[1 2 3 4 5]]]
>>> Пояснення:
- Це тривимірний масив (тензор). Форма показує кількість блоків, рядків і стовпців: (1, 1, 5).
-=--=--=--=--=--=--=--=--=--=-
>>>>> Створіть власні масиви з різною кількістю елементів та використайте метод shape для визначення їх вимірів.
Масив 1 (вектор):
Значення: [10 20 30]
Форма (shape): (3,)
>>> Одновимірний масив, форма показує кількість елементів у ньому.

Масив 2 (матриця):
Значення: 
[[1 2]
 [3 4]]
Форма (shape): (2, 2)
>>> Двовимірний масив (матриця), форма показує кількість рядків і стовпців.

Ма

# Indexing and Slicing

In [64]:

# Початковий масив
F = np.array([1, 1, 2, 3, 5, 8, 13, 21])

# Основна інформація про масив
print(f"""Масив: {F}
Виміри: {F.shape}
Пам'ятаємо, що номерація індексів у масивах починається з 0.
Тому перший елемент масиву: {F[0]} 
Другий: {F[1]}
Останній елемент за звичайним індексом {len(F)}-го порядку: {F[7]}""")

# Від'ємні індекси
print(f"""Можемо скористатись від'ємними індексами, якщо хочемо доступитись до елементів з кінця масиву.
Останній елемент: {F[-1]} 
Передостанній: {F[-2]}""")

print(">>> Пояснення:")
print("- Звичайні індекси (0, 1, 2...) дозволяють отримувати елементи з початку масиву.")
print("- Від'ємні індекси (-1, -2...) зручні для доступу до елементів із кінця масиву.")
print("- Важливо пам'ятати, що перший індекс починається з 0, а не з 1.")
print("-=-" * 10)

# Завдання: практичний доступ до елементів
print(">>>>> Попрактикуйтесь доступатись до елементів, виведіть декілька елементів різними способами:")

# Різні способи доступу до елементів
print(f"Третій елемент (звичайний індекс): {F[2]}")
print(f"Передостанній елемент (від'ємний індекс): {F[-2]}")
print(f"Елемент із середини (наприклад, 4-й): {F[3]}")

# Доступ до кількох елементів через зрізи
print(f"Перші три елементи (зріз [0:3]): {F[0:3]}")
print(f"Останні три елементи (зріз [-3:]): {F[-3:]}")
print(f"Елементи з парними індексами (зріз [::2]): {F[::2]}")
print(f"Елементи зворотного порядку (зріз [::-1]): {F[::-1]}")

# Пояснення до зрізів
print(">>> Пояснення до зрізів:")
print("- `[0:3]`: від 0-го до 2-го індекса включно (3-й не включається).")
print("- `[-3:]`: від -3-го (третій з кінця) до кінця масиву.")
print("- `[::2]`: всі елементи з кроком 2, починаючи з 0-го індекса.")
print("- `[::-1]`: всі елементи у зворотному порядку.")
print("-=-" * 10)


Масив: [ 1  1  2  3  5  8 13 21]
Виміри: (8,)
Пам'ятаємо, що номерація індексів у масивах починається з 0.
Тому перший елемент масиву: 1 
Другий: 1
Останній елемент за звичайним індексом 8-го порядку: 21
Можемо скористатись від'ємними індексами, якщо хочемо доступитись до елементів з кінця масиву.
Останній елемент: 21 
Передостанній: 13
>>> Пояснення:
- Звичайні індекси (0, 1, 2...) дозволяють отримувати елементи з початку масиву.
- Від'ємні індекси (-1, -2...) зручні для доступу до елементів із кінця масиву.
- Важливо пам'ятати, що перший індекс починається з 0, а не з 1.
-=--=--=--=--=--=--=--=--=--=-
>>>>> Попрактикуйтесь доступатись до елементів, виведіть декілька елементів різними способами:
Третій елемент (звичайний індекс): 2
Передостанній елемент (від'ємний індекс): 13
Елемент із середини (наприклад, 4-й): 3
Перші три елементи (зріз [0:3]): [1 1 2]
Останні три елементи (зріз [-3:]): [ 8 13 21]
Елементи з парними індексами (зріз [::2]): [ 1  2  5 13]
Елементи зворотного порядку 

In [73]:

# Початковий масив
A = np.array([[3.4, 8.7, 9.9], 
              [1.1, -7.8, -0.7],
              [4.1, 12.3, 4.8],
              [7.0, -3.9, 5.1]])

# Інформація про масив
print(f"""Масив:
{A}
Виміри (rows, columns): {A.shape}

>>> Як працює доступ до елементів масиву:
- Якщо задати одне значення індексу, то вибирається цілий рядок:
    Перший рядок: {A[0]}
    Останній рядок: {A[-1]}

- Щоб вибрати стовпець, використовується `:` для рядків:
    Перший стовпець: {A[:, 0]}
    Останній стовпець: {A[:, -1]}

- Щоб вибрати конкретний елемент, потрібно вказати два індекси (рядок, стовпець):
    Перший елемент: {A[0][0]} або {A[0, 0]}
    Останній елемент: {A[3][2]} або {A[-1][-1]} або {A[3, -1]}
""")

print(">>> Пояснення:")
print("- `[row_index]`: вибирається весь рядок із заданим індексом.")
print("- `[:, col_index]`: вибираються всі рядки для заданого стовпця.")
print("- `[row_index, col_index]`: вибирається конкретний елемент на перетині рядка і стовпця.")
print("-=-" * 10)

# Завдання: практикуємося з доступом до багатовимірного масиву
print(">>>>> Попрактикуйтесь у доступі до багатовимірного масиву, виведіть елементи, які належать діагоналі:")

# Виведення елементів головної діагоналі
diag_main = [A[i, i] for i in range(min(A.shape))]
print(f"Елементи головної діагоналі: {diag_main}")

# Виведення елементів побічної діагоналі
diag_side = [A[i, -i-1] for i in range(min(A.shape))]
print(f"Елементи побічної діагоналі: {diag_side}")

# Пояснення
print(">>> Пояснення до діагоналей:")
print("- Для головної діагоналі індекси збігаються: `[i, i]`.")
print("- Для побічної діагоналі використовуємо індекси `[i, -i-1]`, де `-i-1` вибирає елементи з кінця в кожному рядку.")
print("- `min(A.shape)` використовується, щоб обмежити кількість елементів, якщо масив не квадратний.")
print("-=-" * 10)


Масив:
[[ 3.4  8.7  9.9]
 [ 1.1 -7.8 -0.7]
 [ 4.1 12.3  4.8]
 [ 7.  -3.9  5.1]]
Виміри (rows, columns): (4, 3)

>>> Як працює доступ до елементів масиву:
- Якщо задати одне значення індексу, то вибирається цілий рядок:
    Перший рядок: [3.4 8.7 9.9]
    Останній рядок: [ 7.  -3.9  5.1]

- Щоб вибрати стовпець, використовується `:` для рядків:
    Перший стовпець: [3.4 1.1 4.1 7. ]
    Останній стовпець: [ 9.9 -0.7  4.8  5.1]

- Щоб вибрати конкретний елемент, потрібно вказати два індекси (рядок, стовпець):
    Перший елемент: 3.4 або 3.4
    Останній елемент: 5.1 або 5.1 або 5.1

>>> Пояснення:
- `[row_index]`: вибирається весь рядок із заданим індексом.
- `[:, col_index]`: вибираються всі рядки для заданого стовпця.
- `[row_index, col_index]`: вибирається конкретний елемент на перетині рядка і стовпця.
-=--=--=--=--=--=--=--=--=--=-
>>>>> Попрактикуйтесь у доступі до багатовимірного масиву, виведіть елементи, які належать діагоналі:
Елементи головної діагоналі: [np.float64(3.4), np.f

In [87]:
# Початковий масив
S = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Інформація про масив та операції доступу до елементів
print(f"""Масив:
{S}
Виміри (len): {S.shape}

>>> Як працює доступ до елементів масиву за допомогою зрізів:
- Беремо декілька елементів з індексами з 2-го по 4-й (не включаючи 5-й):
  {S[2:5]} 
- Всі елементи до 4-го індексу (не включаючи):
  {S[:4]} 
- Всі елементи з 6-го індексу до кінця:
  {S[6:]} 
- Всі елементи масиву:
  {S[:]}

>>> Пояснення до зрізів:
- `[start:end]`: виводить елементи від `start` до `end`, але не включаючи `end`.
- `[:end]`: виводить елементи від початку до `end`, але не включаючи його.
- `[start:]`: виводить елементи від `start` до кінця масиву.
- `[:]`: виводить всі елементи масиву.
""")

# Завдання: практикуємося з витягуванням елементів
print(">>>>> Попрактикуйтесь у витягуванні елементів, візьміть 4 значення з кінця масиву:")

# Витягнути останні 4 елементи масиву
last_four_elements = S[-4:]
print(f"Останні 4 елементи: {last_four_elements}")

# Пояснення
print(">>> Пояснення до зрізу [-4:]:")
print("- `[-4:]`: вибирає останні 4 елементи з масиву, починаючи з 4-го елемента з кінця.")
print("- За допомогою від'ємних індексів ми можемо легко доступити елементи з кінця масиву.")


Масив:
[0 1 2 3 4 5 6 7 8 9]
Виміри (len): (10,)

>>> Як працює доступ до елементів масиву за допомогою зрізів:
- Беремо декілька елементів з індексами з 2-го по 4-й (не включаючи 5-й):
  [2 3 4] 
- Всі елементи до 4-го індексу (не включаючи):
  [0 1 2 3] 
- Всі елементи з 6-го індексу до кінця:
  [6 7 8 9] 
- Всі елементи масиву:
  [0 1 2 3 4 5 6 7 8 9]

>>> Пояснення до зрізів:
- `[start:end]`: виводить елементи від `start` до `end`, але не включаючи `end`.
- `[:end]`: виводить елементи від початку до `end`, але не включаючи його.
- `[start:]`: виводить елементи від `start` до кінця масиву.
- `[:]`: виводить всі елементи масиву.

>>>>> Попрактикуйтесь у витягуванні елементів, візьміть 4 значення з кінця масиву:
Останні 4 елементи: [6 7 8 9]
>>> Пояснення до зрізу [-4:]:
- `[-4:]`: вибирає останні 4 елементи з масиву, починаючи з 4-го елемента з кінця.
- За допомогою від'ємних індексів ми можемо легко доступити елементи з кінця масиву.


In [95]:

# Початковий масив
A = np.array([
    [11, 12, 13, 14, 15],
    [21, 22, 23, 24, 25],
    [31, 32, 33, 34, 35],
    [41, 42, 43, 44, 45],
    [51, 52, 53, 54, 55]
])

# Інформація про масив та операції доступу до елементів
print(f"""Масив:
{A}
Виміри (rows, columns): {A.shape}

>>> Як працює доступ до елементів багатовимірного масиву:
- Беремо декілька рядків (від 0 до 2): {A[0:2]} 
  - Вибирається перші два рядки масиву (індекси 0 і 1).
- Два перші стовпці: {A[:, 0:2]} 
  - Вибираються всі рядки для перших двох стовпців.
- Два останні рядки: {A[3:, :]} 
  - Вибираються останні два рядки (від індексу 3 до кінця).
- Беремо підматрицю (нижні елементи): {A[-3:, -3:]} 
  - Вибираються останні три рядки та останні три стовпці.
""")

# Завдання: практикуємося з витягуванням елементів
print(">>>>> Попрактикуйтесь у витягуванні елементів, візьміть матрицю 2х2 з нижнього та верхнього кутка матриці А:")

# Витягнення підматриці 2x2 з верхнього лівого кута
top_left = A[:2, :2]
# Витягнення підматриці 2x2 з нижнього правого кута
bottom_right = A[-2:, -2:]

print(f"Матриця 2x2 з верхнього лівого кута:\n{top_left}")
print(f"Матриця 2x2 з нижнього правого кута:\n{bottom_right}")

# Пояснення
print(">>> Пояснення до зрізів:")
print("- `[:2, :2]` вибирає перші два рядки та два стовпці з верхнього лівого кута.")
print("- `[-2:, -2:]` вибирає останні два рядки та два стовпці з нижнього правого кута.")
print("- Для вибору підматриць використовуються комбінації індексів рядків і стовпців, де `:` позначає всі елементи в межах заданого діапазону.")


Масив:
[[11 12 13 14 15]
 [21 22 23 24 25]
 [31 32 33 34 35]
 [41 42 43 44 45]
 [51 52 53 54 55]]
Виміри (rows, columns): (5, 5)

>>> Як працює доступ до елементів багатовимірного масиву:
- Беремо декілька рядків (від 0 до 2): [[11 12 13 14 15]
 [21 22 23 24 25]] 
  - Вибирається перші два рядки масиву (індекси 0 і 1).
- Два перші стовпці: [[11 12]
 [21 22]
 [31 32]
 [41 42]
 [51 52]] 
  - Вибираються всі рядки для перших двох стовпців.
- Два останні рядки: [[41 42 43 44 45]
 [51 52 53 54 55]] 
  - Вибираються останні два рядки (від індексу 3 до кінця).
- Беремо підматрицю (нижні елементи): [[33 34 35]
 [43 44 45]
 [53 54 55]] 
  - Вибираються останні три рядки та останні три стовпці.

>>>>> Попрактикуйтесь у витягуванні елементів, візьміть матрицю 2х2 з нижнього та верхнього кутка матриці А:
Матриця 2x2 з верхнього лівого кута:
[[11 12]
 [21 22]]
Матриця 2x2 з нижнього правого кута:
[[44 45]
 [54 55]]
>>> Пояснення до зрізів:
- `[:2, :2]` вибирає перші два рядки та два стовпці з верхн

In [106]:

# Створення масиву 4x7
A = np.arange(28).reshape(4, 7)

# Інформація про масив та операції доступу до елементів
print(f"""Масив:
{A}
Виміри (rows, columns): {A.shape}

>>> Як працює доступ до елементів багатовимірного масиву:
- Беремо кожен другий елемент першого рядка: {A[0, ::2]} 
  - Використовуємо зріз з кроком 2 для рядка 0. Це вибирає елементи з індексами 0, 2, 4, 6.
  
- Беремо кожен третій елемент першого рядка: {A[0, ::3]} 
  - Використовуємо зріз з кроком 3 для рядка 0. Це вибирає елементи з індексами 0, 3, 6.
  
- Кожен другий елемент в кожному другому рядку: {A[::2, ::2]} 
  - Зріз по рядках і стовпцях, що вибирає кожен другий рядок і кожен другий стовпець.

- Останні три елементи в кожному другому рядку: {A[::2, 4:]} 
  - Зріз по рядках вибирає кожен другий рядок, а зріз по стовпцях вибирає елементи з індексів 4 до кінця.

- Можна повністю змінити порядок елементів (дзеркально обернемо): {A[::-1, ::-1]} 
  - Оператор `[::-1]` змінює порядок елементів в масиві (обертає його в зворотному порядку).
""")

# Завдання: практикуємося з витягуванням елементів
print(">>>>> Попрактикуйтесь у витягуванні елементів, будь-яка робоча комбінація:")

# Приклад комбінації: вибір кожного 3-го елемента з другого і четвертого рядків
custom_slice = A[1:4:2, ::3]
print(f"Комбінація: кожен третій елемент з другого та четвертого рядків:\n{custom_slice}")

# Пояснення
print(">>> Пояснення до комбінації:")
print("- `A[1:4:2, ::3]` — вибирає кожен третій елемент з другого та четвертого рядків.")
print("- В першій частині зрізу `1:4:2` ми вибираємо рядки з індексами 1 і 3 (кожен другий рядок від другого до четвертого).")
print("- У другій частині зрізу `::3` ми вибираємо кожен третій стовпець для вибраних рядків.")


Масив:
[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]]
Виміри (rows, columns): (4, 7)

>>> Як працює доступ до елементів багатовимірного масиву:
- Беремо кожен другий елемент першого рядка: [0 2 4 6] 
  - Використовуємо зріз з кроком 2 для рядка 0. Це вибирає елементи з індексами 0, 2, 4, 6.
  
- Беремо кожен третій елемент першого рядка: [0 3 6] 
  - Використовуємо зріз з кроком 3 для рядка 0. Це вибирає елементи з індексами 0, 3, 6.
  
- Кожен другий елемент в кожному другому рядку: [[ 0  2  4  6]
 [14 16 18 20]] 
  - Зріз по рядках і стовпцях, що вибирає кожен другий рядок і кожен другий стовпець.

- Останні три елементи в кожному другому рядку: [[ 4  5  6]
 [18 19 20]] 
  - Зріз по рядках вибирає кожен другий рядок, а зріз по стовпцях вибирає елементи з індексів 4 до кінця.

- Можна повністю змінити порядок елементів (дзеркально обернемо): [[27 26 25 24 23 22 21]
 [20 19 18 17 16 15 14]
 [13 12 11 10  9  8  7]
 [ 6  5  4  3  2  1  0]

In [118]:
import numpy as np

# Створюємо масив від 0 до 49
A = np.arange(50)

# Умова для вибору парних чисел
all_even = (A % 2 == 0)  # Визначаємо парні числа (числа, які діляться на 2 без залишку)

# Більш комплексна умова: числа менші за 30 і діляться на 5 до числа менше за 10
complex = (A < 30) & (A / 5 < 2) 

print(f"""Спочатку потрібно створити умову за якою здійснювати вибірку.
Результат умови буде або {all_even[0]} для {A[0]} або {all_even[1]} для {A[1]}.
- Ось пояснення:
  - Для {A[0]} (0) умова парності виконується, тому що 0 % 2 == 0.
  - Для {A[1]} (1) умова не виконується, бо 1 % 2 != 0.
  
Після підставляння умови пошуку парних чисел в масив отримаємо:
{A[all_even]}
- Це всі парні числа з масиву A.

Або застосувавти більш комплексну умову з двох порівнянь:
{A[complex]}
- Тут ми отримуємо числа, які менші за 30 і діляться на 5, але результат ділення менший за 10. 
  Це числа, що задовольняють обидві умови одночасно.
""")

# Завдання: вивести всі непарні числа з даного масиву.
homework("Виведіть всі непарні числа з даного масиву.")

# Виконання завдання: виводимо непарні числа
all_odd = (A % 2 != 0)  # Умова для непарних чисел
print(f"Непарні числа з масиву A: {A[all_odd]}")


Спочатку потрібно створити умову за якою здійснювати вибірку.
Результат умови буде або True для 0 або False для 1.
- Ось пояснення:
  - Для 0 (0) умова парності виконується, тому що 0 % 2 == 0.
  - Для 1 (1) умова не виконується, бо 1 % 2 != 0.
  
Після підставляння умови пошуку парних чисел в масив отримаємо:
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48]
- Це всі парні числа з масиву A.

Або застосувавти більш комплексну умову з двох порівнянь:
[0 1 2 3 4 5 6 7 8 9]
- Тут ми отримуємо числа, які менші за 30 і діляться на 5, але результат ділення менший за 10. 
  Це числа, що задовольняють обидві умови одночасно.


>>>>> Виведіть всі непарні числа з даного масиву. 

Непарні числа з масиву A: [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]


# Функції для створення матриць: ones, zeros, identity, eye, empty

In [128]:
import numpy as np

# Створюємо різні типи масивів:
o = np.ones(5)  # Масив, де всі елементи рівні 1
z = np.zeros(5)  # Масив, де всі елементи рівні 0
i = np.identity(5)  # Одинична матриця розміру 5x5
e = np.eye(5)  # Одинична матриця, але з можливістю зміщення діагоналі
t = np.empty(5)  # Масив з неініціалізованими значеннями

print(f"""
Всі елементи 1:
{o}
- Масив, де всі елементи 1. Використано функцію np.ones, яка створює масив заданого розміру з усіма одиницями.

Всі елементи 0:
{z}
- Масив, де всі елементи 0. Використано функцію np.zeros, яка створює масив заданого розміру з усіма нулями.

Матриця в якої діагональ всі 1:
{i}
- Одинична матриця розміру 5x5. np.identity(5) створює таку матрицю, де одиниці знаходяться тільки на діагоналі, решта елементи 0.

Також, діагональ всі 1 (зменшимо вивід):
{e[:2, :2]}
- Одинична матриця з меншою частиною виводу для демонстрації. Використано np.eye(5), щоб створити одиничну матрицю розміру 5x5, потім виведено лише перші два рядки та стовпці для скороченого показу.

Пуста матриця буде містити набір випадкових чисел, які записані у пам'ять де був ініціалізований масив:
{t}
- Масив створений за допомогою np.empty, який не ініціалізує елементи і заповнює їх випадковими значеннями, що вже знаходяться у пам'яті (тобто не є нулями чи одиницями).
""")



Всі елементи 1:
[1. 1. 1. 1. 1.]
- Масив, де всі елементи 1. Використано функцію np.ones, яка створює масив заданого розміру з усіма одиницями.

Всі елементи 0:
[0. 0. 0. 0. 0.]
- Масив, де всі елементи 0. Використано функцію np.zeros, яка створює масив заданого розміру з усіма нулями.

Матриця в якої діагональ всі 1:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
- Одинична матриця розміру 5x5. np.identity(5) створює таку матрицю, де одиниці знаходяться тільки на діагоналі, решта елементи 0.

Також, діагональ всі 1 (зменшимо вивід):
[[1. 0.]
 [0. 1.]]
- Одинична матриця з меншою частиною виводу для демонстрації. Використано np.eye(5), щоб створити одиничну матрицю розміру 5x5, потім виведено лише перші два рядки та стовпці для скороченого показу.

Пуста матриця буде містити набір випадкових чисел, які записані у пам'ять де був ініціалізований масив:
[0. 0. 0. 0. 0.]
- Масив створений за допомогою np.empty, який не ініціалізує елементи і зап