# Робота з бібліотекою Numpy




In [12]:

%pip install numpy
def homework(message):
    print("\n>>>>>", message, "\n")


import numpy as np

# Створюємо список температур
temperature = [20.1, 20.1, 20.2, 20.4]
print(f"Оригінальний список temperature: {temperature}")


# Множимо список на 5
t1 = temperature * 5
print(f"При множенні списку temperature на 5 маємо дублювання елементів: {t1}")

homework("Чому маємо такий результат?")
homework( """У Python множення списку на число дублює список,
    а не множить його елементи. Тому результатом є новий список 
    із повторенням елементів початкового списку.?""")

# Множимо кожен елемент списку на 5 за допомогою list comprehension
t1 = [x * 5 for x in temperature]
print(f"Тепер кожен елемент списку множиться на 5: {t1}")

homework("Чому тепер множення успішне?")
homework("""Спискове включення (list comprehension) ітеративно проходить
          кожен елемент списку та виконує над ним арифметичну операцію.
          Таким чином, кожен елемент множиться на 5, і створюється новий список.""")


# Конвертуємо список temperature у NumPy-масив
t2 = np.array(temperature)
print(f"Конвертація списку temperature у NumPy-масив: {t2}")


# Множимо NumPy-масив на 5
t3 = t2 * 5
print(f"При множенні NumPy-масиву на 5 отримуємо: {t3}")



Note: you may need to restart the kernel to use updated packages.
Оригінальний список temperature: [20.1, 20.1, 20.2, 20.4]
При множенні списку temperature на 5 маємо дублювання елементів: [20.1, 20.1, 20.2, 20.4, 20.1, 20.1, 20.2, 20.4, 20.1, 20.1, 20.2, 20.4, 20.1, 20.1, 20.2, 20.4, 20.1, 20.1, 20.2, 20.4]

>>>>> Чому маємо такий результат? 


>>>>> У Python множення списку на число дублює список,
    а не множить його елементи. Тому результатом є новий список 
    із повторенням елементів початкового списку.? 

Тепер кожен елемент списку множиться на 5: [100.5, 100.5, 101.0, 102.0]

>>>>> Чому тепер множення успішне? 


>>>>> Спискове включення (list comprehension) ітеративно проходить
          кожен елемент списку та виконує над ним арифметичну операцію.
          Таким чином, кожен елемент множиться на 5, і створюється новий список. 

Конвертація списку temperature у NumPy-масив: [20.1 20.1 20.2 20.4]
При множенні NumPy-масиву на 5 отримуємо: [100.5 100.5 101.  102. ]


# Вектори, створення та робота з ними

In [16]:

print("Все можна створити вручну за допомогою методу np.array, передавши йому набір значень у вигляді List:")

# Створюємо рядковий вектор
vector_row = np.array([[1, -5, 3, 2, 4]])
print(f"Рядковий вектор (1 рядок, 5 колонок): {vector_row}")  
print(f"Розмір вектора: {vector_row.shape}")
# Пояснення: Масив `vector_row` містить 1 рядок і 5 елементів (стовпчиків).
# `shape` повертає розмір масиву: (1, 5), що означає 1 рядок і 5 колонок.

# Створюємо стовпчиковий вектор
vector_column = np.array([[1], 
                          [2], 
                          [3], 
                          [4]])
print(f"\nСтовпчиковий вектор (4 рядки, 1 колонка):\n{vector_column}")
print(f"Розмір вектора: {vector_column.shape}")
# Пояснення: Масив `vector_column` містить 4 рядки і 1 колонку.
# `shape` повертає розмір масиву: (4, 1), що означає 4 рядки і 1 колонка.





Все можна створити вручну за допомогою методу np.array, передавши йому набір значень у вигляді List:
Рядковий вектор (1 рядок, 5 колонок): [[ 1 -5  3  2  4]]
Розмір вектора: (1, 5)

Стовпчиковий вектор (4 рядки, 1 колонка):
[[1]
 [2]
 [3]
 [4]]
Розмір вектора: (4, 1)


# Метод arange 

In [18]:
# Початкові значення
start = 5
size_of_vec = 100

# Генерація діапазонів
x = range(size_of_vec)
a = np.arange(size_of_vec)
print(f"Масив згенерований простим range: {list(x)[0:5]} та методом arange: {a[0:5]}")
print(">>> Виведено перші п'ять елементів обох масивів. Range повертає об'єкт і потрібно обгорнути в list для перегляду.")

# Завдання
print(">>>>> Виведіть весь діапазон чисел.")
print(f"Весь діапазон range: {list(x)}")
print(f"Весь діапазон arange: {a}")

# Генерація з заданим початком
a = np.arange(start, size_of_vec)
print(f"Можемо задавати початок генерації вектора, перший елемент: {a[0]}")
print(">>> Початок вектора задається параметром 'start'. У цьому випадку перший елемент масиву дорівнює 5.")

# Завдання
print(">>>>> Виведіть останній діапазон в згенерованому масиві.")
print(f"Останні п'ять елементів: {a[-5:]}")

# Діапазон через функцію range
x = range(start, size_of_vec)
print("Те саме, але з вбудованою функцією range:", list(x))
print("Власне вивід значень:", list(x)[0])
print(">>> З range результат ідентичний, але це вбудована функція Python, яка працює для цілих чисел.")

# Завдання
print(">>>>> Виведіть якесь число з середини діапазону.")
print(f"Число з середини: {list(x)[len(x) // 2]}")

# Дробові числа
x = np.arange(10.4)
print("Будем мати:", x)
print(">>> Масив генерується до вказаного значення 10.4, але останній елемент менший за 10.4, бо np.arange генерує діапазон [start, stop).")

# Крок 0.5
x = np.arange(0.5, 4, 0.5)
print("З кроком 0.5:", x)
print(">>> Крок визначає різницю між сусідніми значеннями. Тут масив генерується від 0.5 до 4 (виключно) з кроком 0.5.")

# Крок 0.08
x = np.arange(0.04, 1.84, 0.08)
print("З кроком 0.08:", x, "\nЗверніть увагу на заокруглення")
print(">>> Числа у float можуть мати похибки через спосіб зберігання чисел з плаваючою комою.")

# Завдання
print(">>>>> Згенеруйте значення, де крок буде мати чотири нулі після коми, яким буде результат?")
x = np.arange(0.0001, 0.001, 0.0001)
print(f"З кроком 0.0001: {x}")
print(">>> Отримали значення з точністю до чотирьох знаків після коми. Переконайтесь, що у результатах немає пропущених значень через похибку.")

# Множення
y = x * 2.5
print("Після перемноження:", y)
print(">>> Кожне значення масиву множиться на 2.5.")

# Завдання
print(">>>>> Піднесіть отримане число до степеня та поділіть на 0.4 - Яким буде результат?")
z = (y ** 2) / 0.4
print(f"Результат: {z}")
print(">>> Кожне значення масиву піднесено до квадрату (y^2) і потім поділено на 0.4.")


Масив згенерований простим range: [0, 1, 2, 3, 4] та методом arange: [0 1 2 3 4]
>>> Виведено перші п'ять елементів обох масивів. Range повертає об'єкт і потрібно обгорнути в list для перегляду.
>>>>> Виведіть весь діапазон чисел.
Весь діапазон range: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]
Весь діапазон arange: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
Можемо задавати початок генер

# Метод linspace

In [25]:
start = 5
size_of_vec = 100

# Генерація чисел за допомогою np.linspace
a = np.linspace(start, size_of_vec)
print(f"Згенерували {len(a)} чисел в діапазоні від {a[0]} до {a[-1]}")
print(">>> За замовчуванням linspace генерує 50 чисел, рівномірно розподілених між start і size_of_vec.")

# Завдання
print(">>>>> Виведіть кожне друге число згенерованого діапазону. Тут буде потрібен цикл :)")
for i in range(1, len(a), 2):
    print(f"Кожне друге число: {a[i]}")

# Зменшення кількості чисел
print("Можна зменшити кількість чисел до 5:")
a = np.linspace(start, size_of_vec, 5)
print(a)
print(">>> Тут генерується 5 чисел, включаючи початкове (start) і кінцеве (size_of_vec), з рівними інтервалами.")

# Завдання
print(">>>>> Збільшіть кількість чисел до 100. Виведіть перших та останніх 10.")
a = np.linspace(start, size_of_vec, 100)
print(f"Перші 10 чисел: {a[:10]}")
print(f"Останні 10 чисел: {a[-10:]}")

# Врахування крайніх значень
print("""Як бачимо перше та останнє значення завжди входять у згенерований діапазон. 
Відповідно при цьому вираховується крок.
Це можна змінити, виключивши останнє значення з визначення діапазону.""")

# Виключення останнього значення
a = np.linspace(start, size_of_vec, 5, endpoint=False)
print(a)
print(">>> Виключення endpoint змінює поведінку: останнє число не входить у масив.")

# Завдання
print(">>>>> Спробуйте самі порахувати крок.")
manual_step = (size_of_vec - start) / 5
print(f"Ручний розрахунок кроку (endpoint=False): {manual_step}")

# Порівняння автоматичних кроків
_, sp_1 = np.linspace(start, size_of_vec, 5, endpoint=True, retstep=True)
_, sp_2 = np.linspace(start, size_of_vec, 5, endpoint=False, retstep=True)
print(f"Для порівняння, ми можемо визначити крок автоматично, у нашому випадку це {sp_1} (endpoint=True) та {sp_2} (endpoint=False)")
print(">>> Автоматичний розрахунок кроку залежить від включення або виключення останнього значення.")




Згенерували 50 чисел в діапазоні від 5.0 до 100.0
>>> За замовчуванням linspace генерує 50 чисел, рівномірно розподілених між start і size_of_vec.
>>>>> Виведіть кожне друге число згенерованого діапазону. Тут буде потрібен цикл :)
Кожне друге число: 6.938775510204081
Кожне друге число: 10.816326530612244
Кожне друге число: 14.693877551020408
Кожне друге число: 18.57142857142857
Кожне друге число: 22.448979591836736
Кожне друге число: 26.3265306122449
Кожне друге число: 30.20408163265306
Кожне друге число: 34.08163265306122
Кожне друге число: 37.95918367346939
Кожне друге число: 41.83673469387755
Кожне друге число: 45.714285714285715
Кожне друге число: 49.59183673469388
Кожне друге число: 53.46938775510204
Кожне друге число: 57.3469387755102
Кожне друге число: 61.224489795918366
Кожне друге число: 65.10204081632654
Кожне друге число: 68.9795918367347
Кожне друге число: 72.85714285714286
Кожне друге число: 76.73469387755102
Кожне друге число: 80.61224489795919
Кожне друге число: 84.48979

# Типи масивів/векторів

In [40]:

# Приклади для аналізу
examples = {
    'Скаляр': np.array(1), 
    'Вектор Рядок': np.array([1, 2, 3]), 
    'Вектор Стовпець': np.array([[1], [2], [3]]), 
    'Матриця': np.array([[1, 2],[3, 4], [5, 6]]),
    'Багатовимірна Матриця': np.array([ [[111, 112], [121, 122]],
                                        [[211, 212], [221, 222]],
                                        [[311, 312], [321, 322]] ])
}

# Аналіз кожного прикладу
for key, value in examples.items():
    print(f"Розглядаємо приклад з {key}. \nЗначення x буде: \n{value}")
    print(f"Тип {key} x: {type(value)}")
    print(f"Розмірність/вимір {key} x (ndim): {np.ndim(value)}")
    print(f"Форма {key} x (shape): {value.shape}")
    print(f"Кількість елементів {key} x (size): {np.size(value)}")
    print(">>> Пояснення:")
    print(f"- `np.ndim` показує кількість вимірів: {np.ndim(value)}. Наприклад, для скаляра це 0 (немає вимірів), для вектора рядка це 1, а для багатовимірної матриці — 3.")
    print(f"- `shape` описує кількість елементів у кожному вимірі. Наприклад, форма скаляра — порожній кортеж (), а форма матриці — (рядки, стовпці).")
    print(f"- Вектори можуть мати різну форму, але їхня розмірність (ndim) все одно буде 1 (рядок) або 2 (стовпець).")
    print("-=-" * 10)

# Завдання
print(">>>>> Як Ви думаєте чому маємо такий результат для функції np.ndim?")
print("""
`np.ndim` повертає кількість вимірів у масиві. Для вектора рядка (наприклад, [1, 2, 3]) це один вимір (ndim=1), 
оскільки елементи розташовані в одній послідовності. 
Для вектора-стовпця ([[1], [2], [3]]) вимірів уже два (ndim=2), бо це матриця з одним стовпцем і кількома рядками. 
`shape` повертає кількість елементів у кожному вимірі, тому значення можуть не співпадати з ndim.""")

print(">>>>> Задайте власні вектори з різними числами.")

# Власні приклади
vector_row = np.array([10, 20, 30, 40])
vector_column = np.array([[100], [200], [300], [400]])
matrix = np.array([[1, 2, 3], [4, 5, 6]])
tensor = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print("Мій Вектор Рядок:")
print(f"Значення: {vector_row}")
print(f"Розмірність: {np.ndim(vector_row)}, Форма: {vector_row.shape}, Кількість елементів: {np.size(vector_row)}")

print("Мій Вектор Стовпець:")
print(f"Значення: \n{vector_column}")
print(f"Розмірність: {np.ndim(vector_column)}, Форма: {vector_column.shape}, Кількість елементів: {np.size(vector_column)}")

print("Моя Матриця:")
print(f"Значення: \n{matrix}")
print(f"Розмірність: {np.ndim(matrix)}, Форма: {matrix.shape}, Кількість елементів: {np.size(matrix)}")

print("Моя Багатовимірна Матриця (Тензор):")
print(f"Значення: \n{tensor}")
print(f"Розмірність: {np.ndim(tensor)}, Форма: {tensor.shape}, Кількість елементів: {np.size(tensor)}")


Розглядаємо приклад з Скаляр. 
Значення x буде: 
1
Тип Скаляр x: <class 'numpy.ndarray'>
Розмірність/вимір Скаляр x (ndim): 0
Форма Скаляр x (shape): ()
Кількість елементів Скаляр x (size): 1
>>> Пояснення:
- `np.ndim` показує кількість вимірів: 0. Наприклад, для скаляра це 0 (немає вимірів), для вектора рядка це 1, а для багатовимірної матриці — 3.
- `shape` описує кількість елементів у кожному вимірі. Наприклад, форма скаляра — порожній кортеж (), а форма матриці — (рядки, стовпці).
- Вектори можуть мати різну форму, але їхня розмірність (ndim) все одно буде 1 (рядок) або 2 (стовпець).
-=--=--=--=--=--=--=--=--=--=-
Розглядаємо приклад з Вектор Рядок. 
Значення x буде: 
[1 2 3]
Тип Вектор Рядок x: <class 'numpy.ndarray'>
Розмірність/вимір Вектор Рядок x (ndim): 1
Форма Вектор Рядок x (shape): (3,)
Кількість елементів Вектор Рядок x (size): 3
>>> Пояснення:
- `np.ndim` показує кількість вимірів: 1. Наприклад, для скаляра це 0 (немає вимірів), для вектора рядка це 1, а для багатовимірн

# Багатовимірні масиви, розуміння вимірів

In [47]:
import numpy as np

# Приклади масивів
examples = {
    '5 рядків': np.array([[1], [2], [3], [4], [5]]),  # Матриця з 5 рядків і 1 стовпця
    '5 стовпців': np.array([[1, 2, 3, 4, 5]]),       # Матриця з 1 рядка і 5 стовпців
    '5 елементів': np.array([[[1, 2, 3, 4, 5]]])     # Тензор розмірності (1, 1, 5)
}

# Аналіз кожного прикладу
for key, value in examples.items():
    print(f"Для {key} маємо shape: {value.shape}")
    print(f"Вигляд масиву: \n{value}")
    print(">>> Пояснення:")
    if len(value.shape) == 2:
        print(f"- Це двовимірний масив (матриця). Форма показує кількість рядків і стовпців: {value.shape}.")
    elif len(value.shape) == 3:
        print(f"- Це тривимірний масив (тензор). Форма показує кількість блоків, рядків і стовпців: {value.shape}.")
    print("-=-" * 10)

# Завдання: створення власних масивів
print(">>>>> Створіть власні масиви з різною кількістю елементів та використайте метод shape для визначення їх вимірів.")

# Власні приклади
my_array_1 = np.array([10, 20, 30])          # Одновимірний масив (вектор)
my_array_2 = np.array([[1, 2], [3, 4]])      # Матриця 2x2
my_array_3 = np.array([[[1, 2]], [[3, 4]]])  # Тривимірний масив (2 блоки по 1x2)

# Аналіз власних масивів
print("Масив 1 (вектор):")
print(f"Значення: {my_array_1}")
print(f"Форма (shape): {my_array_1.shape}")
print(">>> Одновимірний масив, форма показує кількість елементів у ньому.")

print("\nМасив 2 (матриця):")
print(f"Значення: \n{my_array_2}")
print(f"Форма (shape): {my_array_2.shape}")
print(">>> Двовимірний масив (матриця), форма показує кількість рядків і стовпців.")

print("\nМасив 3 (тензор):")
print(f"Значення: \n{my_array_3}")
print(f"Форма (shape): {my_array_3.shape}")
print(">>> Тривимірний масив, форма показує кількість блоків, рядків і стовпців у кожному блоці.")


Для 5 рядків маємо shape: (5, 1)
Вигляд масиву: 
[[1]
 [2]
 [3]
 [4]
 [5]]
>>> Пояснення:
- Це двовимірний масив (матриця). Форма показує кількість рядків і стовпців: (5, 1).
-=--=--=--=--=--=--=--=--=--=-
Для 5 стовпців маємо shape: (1, 5)
Вигляд масиву: 
[[1 2 3 4 5]]
>>> Пояснення:
- Це двовимірний масив (матриця). Форма показує кількість рядків і стовпців: (1, 5).
-=--=--=--=--=--=--=--=--=--=-
Для 5 елементів маємо shape: (1, 1, 5)
Вигляд масиву: 
[[[1 2 3 4 5]]]
>>> Пояснення:
- Це тривимірний масив (тензор). Форма показує кількість блоків, рядків і стовпців: (1, 1, 5).
-=--=--=--=--=--=--=--=--=--=-
>>>>> Створіть власні масиви з різною кількістю елементів та використайте метод shape для визначення їх вимірів.
Масив 1 (вектор):
Значення: [10 20 30]
Форма (shape): (3,)
>>> Одновимірний масив, форма показує кількість елементів у ньому.

Масив 2 (матриця):
Значення: 
[[1 2]
 [3 4]]
Форма (shape): (2, 2)
>>> Двовимірний масив (матриця), форма показує кількість рядків і стовпців.

Ма